@startuml usecase
left to right direction
skinparam packageStyle rectangle

actor "Người dùng" as User
actor "Quản trị viên" as Admin

rectangle "Hệ thống Nhận diện Ngôn ngữ Ký hiệu" {
    usecase "Đăng ký / Đăng nhập" as UC1
    usecase "Xem hướng dẫn sử dụng" as UC2
    usecase "Nhận diện qua Camera (Real-time)" as UC3
    usecase "Trích xuất tọa độ 21 điểm tay" as UC3_1
    usecase "Lưu lịch sử nhận diện" as UC4
    usecase "Xem lịch sử cá nhân" as UC5
    
    usecase "Quản lý danh mục ký hiệu (CRUD)" as UC6
    usecase "Quản lý tài khoản người dùng" as UC7
    usecase "Thống kê hệ thống" as UC8
}

User --> UC1
User --> UC2
User --> UC3
User --> UC4
User --> UC5

UC3 ..> UC3_1 : <<include>>

Admin --> UC1
Admin --> UC6
Admin --> UC7
Admin --> UC8
Admin --|> User
@enduml